version: "3.9"
services:
  server1:
    build: .
    environment:
      - PORT=3001
      - NAME=Server 1
    ports:
      - "3001:3001"

  server2:
    build: .
    environment:
      - PORT=3002
      - NAME=Server 2
    ports:
      - "3002:3002"

  server3:
    build: .
    environment:
      - PORT=3003
      - NAME=Server 3
    ports:
      - "3003:3003"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - server1
      - server2
      - server3